import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Page from "../../components/print/Page";
import Role from "../../components/print/Role";

import characters from "~/data/characters/trouble_brewing";

const PrintScriptPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Trouble Brewing</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col items-center justify-center bg-black">
        <Page className="overflow-hidden">
          <div
            style={{ backgroundImage: "url('/images/tb/sheet.webp')" }}
            className="script h-full w-full"
          >
            <Image
              src="/images/tb/logo.webp"
              width={1000}
              height={50}
              className="logo"
              alt="logo"
            />
            <div className="town-side side flex items-center justify-center font-script-title uppercase text-amber-200">
              cittadini
            </div>
            <div className="town columns-2 pr-8 pt-3">
              <Role {...characters.librarian} />
              <Role {...characters.undertaker} />
              <Role {...characters.chef} />
              <Role {...characters.raven_keeper} />
              <Role {...characters.empath} />
              <Role {...characters.fortune_teller} />
              <Role {...characters.investigator} />
              <Role {...characters.washerwoman} />
              <Role {...characters.monk} />
              <Role {...characters.mayor} />
              <Role {...characters.soldier} />
              <Role {...characters.virgin} />
              <Role {...characters.slayer} />
            </div>
            <div className="town -ml-10 w-80 border-b-2 border-black/50"></div>
            <div className="out-side side flex items-center justify-center font-script-title uppercase text-amber-200">
              emarginati
            </div>
            <div className="out columns-2 pr-8 pt-6">
              <Role {...characters.butler} />
              <Role {...characters.recluse} />
              <Role {...characters.saint} />
              <Role {...characters.drunk} />
            </div>
            <div className="out -ml-10 w-80 border-b-2 border-black/50"></div>
            <div className="minions-side side flex items-center justify-center font-script-title uppercase text-amber-200">
              seguaci
            </div>
            <div className="minions columns-2 pr-8 pt-6">
              <Role {...characters.poisoner} />
              <Role {...characters.baron} />
              <Role {...characters.scarlet_woman} />
              <Role {...characters.spy} />
            </div>
            <div className="minions -ml-10 w-80 border-b-2 border-black/50"></div>
            <div className="demons-side side mt-4 flex items-center justify-end font-script-title uppercase text-amber-200">
              demoni
            </div>
            <div className="demons relative  columns-2 pt-6">
              <Role {...characters.imp} />
              <div
                className="absolute bottom-0 -left-10 flex h-[110px] w-full items-end"
                style={{ gridArea: "bottom" }}
              >
                <Image src="/images/tb/sheet-bottom.webp" fill alt="bottom" />
                <div className="absolute bottom-2 ml-[30px] flex w-full justify-center font-serif">
                  <p className="block w-24 text-center text-sm text-black/60">
                    * Non la Prima Notte
                  </p>
                </div>
              </div>
            </div>
          </div>
        </Page>
      </main>
    </>
  );
};

export default PrintScriptPage;
