import { type NextPage } from "next";
import Head from "next/head";
import Page from "~/components/print/Page";
import Token from "~/components/print/Token";

import characters from "~/data/characters/trouble_brewing";

const PrintTokenPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Trouble Brewing</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col items-center justify-center bg-black">
        <Page className="py-[0.5cm]">
          <div className="flex justify-around">
            <Token {...characters.washerwoman} />
            <Token {...characters.librarian} />
            <Token {...characters.investigator} />
            <Token {...characters.chef} />
          </div>
          <div className="-mt-4 flex justify-center gap-6">
            <Token {...characters.empath} />
            <Token {...characters.fortune_teller} />
            <Token {...characters.undertaker} />
          </div>
          <div className="-mt-4 flex justify-around">
            <Token {...characters.monk} />
            <Token {...characters.raven_keeper} />
            <Token {...characters.virgin} />
            <Token {...characters.slayer} />
          </div>
          <div className="-mt-4 flex justify-center gap-6">
            <Token {...characters.mayor} />
            <Token {...characters.soldier} />
            <Token {...characters.butler} />
          </div>
          <div className="-mt-4 flex justify-around">
            <Token {...characters.recluse} />
            <Token {...characters.drunk} />
            <Token {...characters.saint} />
            <Token {...characters.poisoner} />
          </div>
          <div className="-mt-4 flex justify-center gap-6">
            <Token {...characters.spy} />
            <Token {...characters.scarlet_woman} />
            <Token {...characters.baron} />
          </div>
          <div className="-mt-4 flex justify-around">
            <div className="aspect-square w-[10.5rem]"></div>
            <Token {...characters.imp} />
            <div className="aspect-square w-[10.5rem]"></div>
            <div className="aspect-square w-[10.5rem]"></div>
          </div>
        </Page>
      </main>
    </>
  );
};

export default PrintTokenPage;
