import { type NextPage } from "next";
import Head from "next/head";
import Page from "~/components/print/Page";
import Token from "~/components/print/Token";

import roles from "~/data/roles/tb";

const PrintTokenPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Trouble Brewing</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col items-center justify-center bg-black">
        <Page className="py-[0.5cm]">
          <div className="flex justify-around">
            <Token {...roles.chef} />
            <Token {...roles.empath} />
            <Token {...roles.fortune_teller} />
            <Token {...roles.investigator} />
          </div>
          <div className="-mt-4 flex justify-center gap-6">
            <Token {...roles.librarian} />
            <Token {...roles.monk} />
            <Token {...roles.mayor} />
          </div>
          <div className="-mt-4 flex justify-around">
            <Token {...roles.raven_keeper} />
            <Token {...roles.slayer} />
            <Token {...roles.soldier} />
            <Token {...roles.undertaker} />
          </div>
          <div className="-mt-4 flex justify-center gap-6">
            <Token {...roles.virgin} />
            <Token {...roles.washerwoman} />
            <Token {...roles.butler} />
          </div>
          <div className="-mt-4 flex justify-around">
            <Token {...roles.drunk} />
            <Token {...roles.recluse} />
            <Token {...roles.saint} />
            <Token {...roles.baron} />
          </div>
          <div className="-mt-4 flex justify-center gap-6">
            <Token {...roles.poisoner} />
            <Token {...roles.scarlet_woman} />
            <Token {...roles.spy} />
          </div>
          <div className="-mt-4 flex justify-around">
            <Token {...roles.imp} />
            <Token label="orologiaio" iconSrc="snv/clockmaker" />
            <Token label="artista" iconSrc="snv/artist" />
            <Token label="imbranato" iconSrc="snv/klutz" />
          </div>
        </Page>
      </main>
    </>
  );
};

export default PrintTokenPage;
