/* eslint-disable @typescript-eslint/no-non-null-assertion */
import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Page from "../components/Page";
import Role from "../components/Role";
import Token from "../components/Token";

type Role = {
  label: string;
  iconSrc: string;
  size?: number;
  evil?: boolean;
  desc: string;
};

const roles = {
  chef: {
    label: "cuoco",
    iconSrc: "tb/chef",
    desc: "Cominci sapendo quante coppie di giocatori malvagi siedono vicini",
  },
  empath: {
    label: "empatica",
    iconSrc: "tb/empath",
    desc: "Ogni notte, sai quanti dei tuoi 2 vicini vivi sono malvagi",
  },
  fortune_teller: {
    label: "indovino",
    iconSrc: "tb/fortuneteller",
    desc: "Ogni notte, scegli 2 giocatori: scopri se uno di loro è il Demone. C'è un giocatore buono che ti risulterà come il Demone",
  },
  investigator: {
    label: "investigatore",
    iconSrc: "tb/investigator",
    desc: "Cominci sapendo che 1 di 2 giocatori indicati è un preciso servitore",
  },
  librarian: {
    label: "bibliotecario",
    iconSrc: "tb/librarian",
    size: 100,
    desc: "Cominci sapendo che 1 di 2 giocatori indicati è un preciso estraneo (o che non c'è ne sono in gioco)",
  },
  monk: {
    label: "monaco",
    iconSrc: "tb/monk",
    desc: "Ogni notte*, scegli un giocatore (te stesso escluso): sono protetti dal Demone stanotte",
  },
  mayor: {
    label: "sindaco",
    iconSrc: "tb/mayor",
    desc: "Se non ci sono esecuzioni con 3 giocatori in vita, la tua squadra vince.<br>Un giocatore potrebbe morire al tuo posto di notte",
  },
  raven_keeper: {
    label: "custode dei corvi",
    iconSrc: "tb/ravenkeeper",
    size: 95,
    desc: "Se muori di notte, scegli un giocatore: scopri il suo ruolo",
  },
  slayer: {
    label: "witcher",
    iconSrc: "tb/slayer",
    desc: "Una volta per gioco, di giorno, scegli pubblicamente un giocatore: se è un Demone muore",
  },
  soldier: {
    label: "soldato",
    iconSrc: "tb/soldier",
    desc: "Siete al sicuro dal Demone",
  },
  undertaker: {
    label: "becchino",
    iconSrc: "tb/undertaker",
    desc: "Ogni notte*, scopri il ruolo di chi è stato giustiziato oggi",
  },
  virgin: {
    label: "vergine",
    iconSrc: "tb/virgin",
    desc: "La 1° volta che vieni nominata, se chi ti ha nominato è un cittadino, verrà giustiziata",
  },
  washerwoman: {
    label: "lavandaia",
    iconSrc: "tb/washerwoman",
    desc: "Cominci sapendo che 1 di 2 giocatori è un preciso cittadino",
  },

  butler: {
    label: "maggiordomo",
    iconSrc: "tb/butler",
    desc: "Ogni notte, scegli un giocatore (te stesso escluso): domani potrai votare solo se egli voterà",
  },
  drunk: {
    label: "ubriacone",
    iconSrc: "tb/drunk",
    desc: "Non sai di essere l'ubriaco. Pensi di essere un cittadino ma la tua abilità malfunziona",
  },
  recluse: {
    label: "recluso",
    iconSrc: "tb/recluse",
    desc: "Potresti risultare come malvagio e come Demone o seguace, anche se morto",
  },
  saint: {
    label: "santo",
    iconSrc: "tb/saint",
    desc: "Se vieni giustiziato, la tua squadra perde",
  },

  baron: {
    label: "barone",
    iconSrc: "tb/baron",
    desc: "Ci sono 2 estranei extra in gioco<br>[+2 Estranei]",
    evil: true,
  },
  poisoner: {
    label: "avvelenatore",
    iconSrc: "tb/poisoner",
    desc: "Ogni notte, scegli un giocatore: stanotte e domani giorni sarà avvelinato",
    evil: true,
  },
  scarlet_woman: {
    label: "donna scarlatta",
    iconSrc: "tb/scarletwoman",
    size: 95,
    desc: "Se ci sono almeno 5 giocatori vivi e il Demone muore, diventi il Demone",
    evil: true,
  },
  spy: {
    label: "spia",
    iconSrc: "tb/spy",
    desc: "Ogni notte, vedi il grimorio. Potresti risultare come buono e paesano o estraneo, anche se morto",
    evil: true,
  },

  imp: {
    label: "diavoletto",
    iconSrc: "tb/imp",
    desc: "Ogni notte*, scegli un giocatore: muore.<br>Se uccidi te stesso, un seguace diventerà il Diavoletto",
    evil: true,
  },
} as const;

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Trouble Brewing</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-black">
        {/* <div className="fixed top-0 left-0 h-[29.7cm] w-[21cm] bg-black/50"></div> */}
        <Page className="hidden py-[0.5cm]">
          <div className="flex justify-around">
            <Token {...roles.chef} />
            <Token {...roles.empath} />
            <Token {...roles.fortune_teller} />
            <Token {...roles.investigator} />
          </div>
          <div className="-mt-4 flex justify-center gap-6">
            <Token {...roles.librarian} />
            <Token {...roles.monk} />
            <Token {...roles.mayor} />
          </div>
          <div className="-mt-4 flex justify-around">
            <Token {...roles.raven_keeper} />
            <Token {...roles.slayer} />
            <Token {...roles.soldier} />
            <Token {...roles.undertaker} />
          </div>
          <div className="-mt-4 flex justify-center gap-6">
            <Token {...roles.virgin} />
            <Token {...roles.washerwoman} />
            <Token {...roles.butler} />
          </div>
          <div className="-mt-4 flex justify-around">
            <Token {...roles.drunk} />
            <Token {...roles.recluse} />
            <Token {...roles.saint} />
            <Token {...roles.baron} />
          </div>
          <div className="-mt-4 flex justify-center gap-6">
            <Token {...roles.poisoner} />
            <Token {...roles.scarlet_woman} />
            <Token {...roles.spy} />
          </div>
          <div className="-mt-4 flex justify-around">
            <Token {...roles.imp} />
            <Token label="orologiaio" iconSrc="snv/clockmaker" />
            <Token label="artista" iconSrc="snv/artist" />
            <Token label="imbranato" iconSrc="snv/klutz" />
          </div>
        </Page>
        <Page className="overflow-hidden">
          <div
            style={{ backgroundImage: "url('/images/tb/sheet.webp')" }}
            className="script h-full w-full"
          >
            <Image
              src="/images/tb/logo.webp"
              width={1000}
              height={50}
              className="logo"
              alt="logo"
            />
            <div className="town-side side flex items-center justify-center font-script-title uppercase text-amber-200">
              cittadini
            </div>
            <div className="town columns-2 pr-8 pt-3">
              <Role {...roles.librarian} />
              <Role {...roles.undertaker} />
              <Role {...roles.chef} />
              <Role {...roles.raven_keeper} />
              <Role {...roles.empath} />
              <Role {...roles.fortune_teller} />
              <Role {...roles.investigator} />
              <Role {...roles.washerwoman} />
              <Role {...roles.monk} />
              <Role {...roles.mayor} />
              <Role {...roles.soldier} />
              <Role {...roles.virgin} />
              <Role {...roles.slayer} />
            </div>
            <div className="town -ml-10 w-80 border-b-2 border-black/50"></div>
            <div className="out-side side flex items-center justify-center font-script-title uppercase text-amber-200">
              estranei
            </div>
            <div className="out columns-2 pr-8 pt-6">
              <Role {...roles.butler} />
              <Role {...roles.recluse} />
              <Role {...roles.saint} />
              <Role {...roles.drunk} />
            </div>
            <div className="out -ml-10 w-80 border-b-2 border-black/50"></div>
            <div className="minions-side side flex items-center justify-center font-script-title uppercase text-amber-200">
              seguaci
            </div>
            <div className="minions columns-2 pr-8 pt-6">
              <Role {...roles.poisoner} />
              <Role {...roles.baron} />
              <Role {...roles.scarlet_woman} />
              <Role {...roles.spy} />
            </div>
            <div className="minions -ml-10 w-80 border-b-2 border-black/50"></div>
            <div className="demons-side side mt-4 flex items-center justify-end font-script-title uppercase text-amber-200">
              demoni
            </div>
            <div className="demons relative  columns-2 pt-6">
              <Role {...roles.imp} />
              <div
                className="absolute bottom-0 -left-10 flex h-[110px] w-full items-end"
                style={{ gridArea: "bottom" }}
              >
                <Image src="/images/tb/sheet-bottom.webp" fill alt="bottom" />
                <div className="absolute bottom-2 ml-[30px] flex w-full justify-center font-serif">
                  <p className="block w-24 text-center text-sm text-black/60">
                    * Non la Prima Notte
                  </p>
                </div>
              </div>
            </div>
          </div>
        </Page>
      </main>
    </>
  );
};

export default Home;
